### ISSUE TITLE
client hosted servers lag when host alt tabs

### ISSUE THREAD

**Issue by Tsunder** [FakeFishGames/Barotrauma#10412]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I host a server using the in-game "host server" option, if/when I alt tab out of baro/switch window focus, the server starts suffering performance issues - rubberbanding everyone by like 0s - 1s of actions, including myself.

console occassionally says server running slowly (usually 56-59 updates/second, but when alt tab, sometimes 30/s has been seen!)

seems to go away at a new round if I keep focus on the game

### Reproduction steps

1. host MP lobby w/ in game menu - 9 people and a large ship, like berilia
2. run round (any mode)
3. host alt tabs

### Bug prevalence

Happens regularly

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
I think this happens with any process that is pushed to background. The resources used on background processes can be affected in the OS settings, but I'm not aware of anything we could do to it. And if there was, I'm not sure what we should do to it. Even if it'd be possible, forcing the system to use full resources on a background process sounds like a bad idea, because it could possibly make the OS unresponsive.
