### ISSUE TITLE
Abandoned outpost not converting to a normal one.

### ISSUE THREAD

**Issue by Wyatt-Warren** [FakeFishGames/Barotrauma#12145]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After doing the "Rescuing Subra" mission at an abandoned outpost, the outpost icon turned red and had no mission associated with it, as usual after completing an abandoned outpost mission, however the outpost stayed abandoned and never became a normal outpost. every other abandoned outpost in the campaign became occupied within a few turns, but this one never converted back.
Attached is my save file, many turns after completing Rescuing Subra.
[Wasdingo.zip](https://github.com/Regalis11/Barotrauma/files/11713354/Wasdingo.zip)

### Reproduction steps

1. Start a campaign (This happened in singleplayer for me)
2. Progress along the cultist questline.
3. Receive the mission "Rescuing Subra" which will be at an abandoned outpost.
4. Complete "Rescuing Subra."
5. Observe as the outpost never converts to a normal outpost.

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0ab4b7d3e966e3bc009f0d86cf8e592eca483af4 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
Works now correctly.
Closing ticket.

**Comment by Necronomicron** [comment]
How many cycles does it take to convert it to normal? Does it require some special actions?

**Comment by Regalis11** [comment]
It takes 2-3 "turns" (or "world steps" as they're called in the codebase). Each turn corresponds to 10 minutes of mission time, and traversing through the entire level always counts as at least one turn, even if you do it in less than 10 minutes.

**Comment by Necronomicron** [comment]
Well, then it must be broken, because I completed more than 3 missions, and each of them was way longer than 10 minutes.
[It also seems I am not alone](https://steamcommunity.com/app/602960/discussions/1/4342103705849819959/).

**Comment by Regalis11** [comment]
Hmm, you're right, I gave this a test myself now and it does seem to be bugged. I found the issue though and was manage to fix it (again).

Commit in our private repo https://github.com/FakeFishGames/Barotrauma-development/commit/2eed44d817aca92901f167c84c5c181b556b0a07:
> Fixed rescuing subra still not changing the outpost back to normal. Happened because the mission is configured to block location type changes, which also prevented triggering the location type change at the end of the mission.

The fix should be coming up in the next update, sorry for the inconvenience!

**Comment by Necronomicron** [comment]
Either it's still not fixed or I am missing something. I tried to travel from an adjacent outpost to another adjacent outpost. I also completed missions on both of those outposts without traveling to another outpost. I grabbed all the missions available, there were no outpost recovery missions. Then I visited bugged outpost.

If it's actually still not fixed, can I change something in my save file to fix it? Because last time I waited for multiple months for an update, I don't want to wait another multiple months. Can I grant myself an outpost recovery missions or something?

Also, when I load or enter one of the adjacent outposts (the one in the savefile below), I get this error: «Failed to connect waypoints between outpost modules. No waypoint in the top gap of the module "ResidentialModule_01_Colony"». This wasn't happening when I played last time in August. But that's probably unrelated bug.

[Save.zip](https://github.com/user-attachments/files/18631493/Save.zip)

**Comment by Regalis11** [comment]
@Necronomicron Unfortunately the fix doesn't automatically make the location type change in existing saves: the issue had to do with the rescue mission not correctly changing the location type when it completes, but in a save where the mission has been completed earlier and no longer exists, the location will remain abandoned. If it's crucial to get the outpost to an unabandoned state, you could for example use the console command "`unlockmission abandonedoutposthumans`" or "`unlockmission abandonedoutpostmudraptor`" in the outpost and then re-enter it to get a mission to appear. Another option would be to use the Barotrauma Save Editor, find the location in question in the file, and change the element `type="abandonedoutpost"` to e.g. `type="outpost"`. Sorry for the inconvenience!

**Comment by Necronomicron** [comment]
Does these console commands affect achievements?
