### ISSUE TITLE
Searchlights do not attract aliens unlike gun lights

### ISSUE THREAD

**Issue by mygamingaccount** [FakeFishGames/Barotrauma#12265]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Gun turrets attract aliens with vision from a great distance.

The same is not true for searchlights, aliens ignore those.

### Reproduction steps

Spawn crawlers near a sub that has the gun lights off, searchlights on.
Use `freecam` and `aitargets` to inspect the AI.

Toggle the gun lights

Expected: crawlers attack the source of bright light regardless of what it's attached to

 Instead they ignore the searchlight.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
Searchlights lack the `<aitarget>` tag

**Comment by itchyOwl** [comment]
Implemented in Regalis11/Barotrauma-development@0dbe382.

**Comment by Jasontti** [comment]
Tested.
Removed turrets, crawlers are attracted to searchlight same as turrets.
Closing ticket.

**Comment by Regalis11** [comment]
This seems to have caused a new issue https://github.com/Regalis11/Barotrauma/issues/12818, so I decided to revert the fix for now. Tagging the searchlight as a turret could cause other side-effects as well, we should at least check it doesn't affect upgrades or swapping.

**Comment by itchyOwl** [comment]
Simple steps to repro:
- Open Humpback in the sub editor.
- Delete the front turrets, so that they don't attract the monsters.
- Start the game in the test mode.
- Enter `power`, `debugai` and `freecam` commands in the console.
- Spawn a crawler in front of the sub. Teleport it closer to the sub until it spots the searchlight. The monster should target the searchlight until it sees the walls (or some other target). If the sub doesn't move, the monster might not immediately see the walls either, in which case it may fall in the idle mode for a short period, because it fails to attack the searchlight and hence ignores it.
![image](https://github.com/user-attachments/assets/7d2e5273-a372-486e-8976-809ec9882b03)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
