### ISSUE TITLE
Joining clients see white names on AI bots if they receive chat messages before fully loading

### ISSUE THREAD

**Issue by ghost** [FakeFishGames/Barotrauma#12318]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Really minor thing, probably.

Under some very special circumstances (server using different language pack OR modded character names; server being much faster than client) it is possible to get wrong name (and profession) in chat:

![20230710032214_1](https://github.com/Regalis11/Barotrauma/assets/81986452/a47d3ce9-b511-4f92-9053-b5c01c474820)

Why It Might Be Important: one more probable source of mysterious desyncs to squash?

### Reproduction steps

Host a multiplayer game on a computer with exceptionally good hardware.
Hire some Captain Hognose and make sure that He's very chatty and start a mission.
Try to join that game using a client on a computer with much more worse hardware.
Make sure that during connection process Captain Hognose IS very chatty.
Upon successful session load for connecting client, witness wrong name (and color from wrong class) in chat.
Bonus points: after successful session load make Captain Hognose say something again, see that this time name and class color shall be correct.

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by NilanthAnimosus** [comment]
Thank you for the report!

Tested on 1.0.21.0

Issue actually appears to be receiving chat messages from bots before characters/character info's are loaded.

To reproduce this issue:

1. Host a server
2. Join with a client and start a round
3. Spawn some AI's in (IE. a mechanic)
4. Give the AI the orders Follow and Wait.
5. Connect and begin to start spectating (To initiate the loading screen)
6. Change the orders (using the previous order) to generate lots of AI text, You will find it is white until loaded which point newer messages will be the job colour (Since the game is loaded now and the characters/info's exist to colour the names).

**Comment by Regalis11** [comment]
This seems to happen when the character doesn't exist client-side yet: the client doesn't know the job of the character or the NPC prefab it's instantiated from, and defaults to white color and the character name used by the server. Seems like a low prio issue to me, but we might take a look at it at some point.

**Comment by itchyOwl** [comment]
Confirmed (low prio) issue -> moving back to icebox
