### ISSUE TITLE
Cant drag nonplayerteaminteractable items as enemy team

### ISSUE THREAD

**Issue by ricky122122** [FakeFishGames/Barotrauma#12768]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I was doing some stuff with separate teams and wanted players to not be able to take off certain weapons/armor from enemy players so I set them to nonplayerteaminteractable="true" it worked only the enemy players can use them and interact with them but they cant drag the items around without using another item to swap places with it

### Reproduction steps

1. put a nonplayerteaminteractable item on a sub
2. start a missions game with pirates selected using the sub with the item on it
3. teleport pirate onto your sub control said pirate and pickup nonplayerteaminteractable item try to drag it into another slot

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by PlasmaUwU** [comment]
I also tried to do this, but as I understood it is not a bug , `nonplayerteaminteractable="true"` this is not a unuse for players from another team, but a unuse for all players (Only bots can use such items)

**Comment by ricky122122** [comment]
if it is suppose to work that way then it would still be a bug since I could use the items as enemy team just not drag them I could also press the unequip button and swap the spots they were in with another item and pick them up. from the name of it tho I figured it was just suppose to be the default player team was not suppose to be able to interact with it I was not default team in this case

**Comment by myrukun** [comment]
player team i assume means any player-controlled humanoid, but I could be wrong

**Comment by Regalis11** [comment]
Thank you for the report! 

The intended behavior is that no-one in the player's crew (either bot or a human player) can interact with the item (i.e. only enemies and outpost NPCs can interact with it). Some of the UI logic (like dragging) didn't check which team the player is in, most likely because we thought it would be safe to assume you're always controlling a character that's in a player team.

Addressed this in https://github.com/Regalis11/Barotrauma-development/commit/c2a1051384b1cf495ae50ba56e38dbcd2d1aaf67 (if you're controlling an enemy, you can drag and otherwise interact with the item normally).
