### ISSUE TITLE
Harpoon gun's unintuitive mechanics

### ISSUE THREAD

**Issue by NotWendy** [FakeFishGames/Barotrauma#12785]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a set of related issues, and some suggestions for fixing them. Sorted from problems and changes that are only concerned with making current mechanics more intuitive, to more drastic balance suggestions that can be implemented on top of simpler fixes.

1.  Harpoon guns have a mechanic of reeling the enemy towards the gun's user, but **the state of pulling/reeling lacks feedback and is easy to miss altogether**. It's also not always clear when the harpoon's wire has been cut off, since the wire itself won't always be clearly visible. The gun could use a new **looping sound effect** and a **change in its crosshair's look** to indicate that it's in the state of reeling a creature in. Making the normal crosshair rotate while reeling could be an intuitive visual indicator, representing an actual spinning reel. Maybe some particles around the gun when it's in the reeling state too?

2. **Reeling controls are completely unintuitive.** Using the right mouse button (normally used for aiming) to reel is not something a player would normally think to do. Perhaps having to hold the left mouse button (the one you pressed to shoot the harpoon) would work better for this mechanic. You are not going to be pressing it again unless you're already done with your current harpoon and want to shoot a new one.

3. **Used harpoons are tricky to retrieve.** The interaction area on them is tiny. Finding a harpoon on the floor is one thing, but actually aligning your cursor with one to pick it up is a whole another challenge. Make the selection box thicker, maybe? If possible.

4. Harpoon gun **being able to hold multiple harpoons at once** (ammo capacity of 6) **adds further complexity** to reeling and reloading. The gun could hold only one harpoon at a time, incentivizing the user to pay more attention to each shot. This relates both to point 2 and 3. Having to reload after each shot creates a natural break between shots, meaning you won't accidentally shoot another harpoon while using your fire button to reel. And reeling could become a new way of automatically reloading the gun, putting a harpoon that is reeled back in after a missed shot back into the gun. (This makes harpoons reusable in even more situations, as they become harder to lose.)

5. **Pulling an enemy towards yourself isn't very useful**, when **most enemies already want to be close to you**. This makes an already hard to understand mechanic even less intuitive, as in a lot of cases engaging with it will actively harm you. Getting hit also prevents you from continuing to hold onto the enemy. Making the target try to flee while it's being reeled in would be a significant change, but it would give harpoons a new, clear purpose as a support tool. With a harpoon you can keep a single target distracted, while not being able to do anything else yourself, until you let go of the harpoon.

### Reproduction steps

1. Shoot an enemy with a harpoon in the middle of a chaotic fight, and hold the right mouse button to reel them in.
2. Notice how there is no intuitive visual or audio indication of the enemy being reeled in.
3. Get eaten, because being close to you is what your enemy wanted.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
1. true, not sure if doable since it's the spear and not the gun that does the reeling

2. no other way to do it

4. requires a lot of rebalancing + takes an extra inventory slot

5. yes, the reeling is useless atm (and sourcepullforce doesnt seem to do anything)

**Comment by WJohn** [comment]
Something to add -- People have been using harpoon guns as basically discount revolvers for a very long time now. The reeling mechanic is a distant, mostly forgotten thing when people just want something to shoot with. With 1.1, revolver are now extremely inexpensive to use, and harpoon guns may very well fall to the wayside if left in their current state.

Having them become a distinctly different support weapon would make them far more useful in everything from controlling fights in a cave, preventing traitors from running away effectively, and being a very safe weapon to hand to your crew due to their limited firepower.

Importantly, this single-shot idea that's being suggested here wouldn't really impact Deep Sea Slayer security officers, harpoon-coil rifles, or Spec-Ops' double damage on full-health enemies. They could still be used for a devastating 200+ damage opening attack.

**Comment by Rotiart-Drol** [comment]
Can you imagine how fun it would be if the tether was strong enough to pull the harpoon user along? If you could hitch a ride on the exterior of a sub or hell even a worm?

**Comment by itchyOwl** [comment]
I agree with most of the feedback here. The reeling feature wasn't really planned, but I decided to keep it after having implemented it for prototyping with the grappling hook mechanics, which we then decided to not to use. 

> Can you imagine how fun it would be if the tether was strong enough to pull the harpoon user along? If you could hitch a ride on the exterior of a sub or hell even a worm?

This used to be a thing. Should work by pressing spacebar while aiming, but it doesn't seem to work anymore. I don't think it ever was removed, but now the rope just seems to snap right when you press the space.

Anyway it was a gimmick at best, because the monsters would still attack you. Making the monsters not target you while you "ride" them might be an interesting feature. Not sure how well it would work balance-wise or if it would open up to some exploits, but maybe worth testing.

> true, not sure if doable since it's the spear and not the gun that does the reeling


Reeling is implemented in the rope component of the spear, but adding a sound to the weapon when the rope is reeling should still be relatively easy. Might require code changes, though.

@JeroonBosch let's have chat about the implementation side when you've done with the design-side.

**Comment by ubertpendragon** [comment]
> This used to be a thing. Should work by pressing spacebar while aiming, but it doesn't seem to work anymore. I don't think it ever was removed, but now the rope just seems to snap right when you press the space.

Something got changed that made sourcepull only work when ragdolled, which is now broken, but I remember being able to change sourcepull based on creature mass

If you harpooned a low mass creature, you'd pull it, if you harpooned a large mass creature, it would pull you

Pulling was however using a fixed value and didnt scale with creature mass or speed, which mean you couldn't just "surf" the hammerhead and the rope would snap if it was too fast



https://github.com/Regalis11/Barotrauma/assets/73229309/55820e80-cbf4-417b-a85e-c1b928a76159

**Comment by JeroonBosch** [comment]
> @JeroonBosch let's have chat about the implementation side when you've done with the design-side.

Sure. Personally I do agree with the comments here either, but I also wouldn't say any of these things really bothered me aside from how difficult it is to pick up harpoons. I have encountered moments where the reeling has been useful, like when a crawler or mudraptor is attacking a crewmember and I am standing behind the monster (so the monster is in the middle): I could prevent the monster from reaching the teammate. It's niche, but not useless.

Doesn't mean we cannot work on the harpoon and improve it though. Especially a reeling sound effect would be good to have.

> Making the target try to flee while it's being reeled in

Less of a fan of this one. It's a very basic and cheap weapon, this could easily make it too powerful. Also I don't really see any reason why a target would try to flee when harpooned.

**Comment by itchyOwl** [comment]
> Also I don't really see any reason why a target would try to flee when harpooned.

Well, they are animals, and animals can get afraid. But yeah, it would probably make sense only on small creatures like crawlers. And they can't pull you anyway. So you could just maybe hold them for a while.

**Comment by itchyOwl** [comment]
Fixed the reeling in Regalis11/Barotrauma-development#4558.

**Comment by Rokvach** [comment]
Tested, no issues. Can be merged and closed.
