### ISSUE TITLE
Bots cancel orders outside of ships

### ISSUE THREAD

**Issue by Arctomachine** [FakeFishGames/Barotrauma#12900]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Bots now cancel orders when they are outside and not under player control. This leads to at least 2 issues:
- when done mining and telling bot to return, previous orders have to be given again when bot returns
- impossible to let bots handle beacon stations

### Reproduction steps

1. Give bot some orders
2. Take control over bot and lead him outside
3. Take control over another character
4. Bot outside cancels orders

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Thanks for your report.

Which orders do you mean? It's intentional that bots abandon orders that they can't or won't follow for some reason.

Many orders are such that they are not allowed outside of sub. E.g. if a bot is ordered to fix leaks, they will response negatively and abandon the order, because it's not allowed outside of the sub.

Some orders, like heal, follow, or return are allowed outside the submarine, but they may be abandoned, if the bot for some reason cannot follow them.

Finally, some orders are not allowed outside of the sub, but are allowed inside any sub, like exinguish fires.

The most recent order should still remain visible and it should be possible to reissue them by clicking them again.

I tested it by giving a bot some orders, taking it outside, and telling it to return back to the sub. Also had another bot with different orders following me. I didn't notice anything out of ordinary: the orders that are not allowed outside of the sub, were abandoned and the orders that were allowed were not.

So, without knowing the details on what's happening in your case, it's not possible to say if it's bugged or intentional, and whether it should be addressed or not.

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/069bbce4-4845-45f7-8d25-0b030f79e223)

**Comment by Arctomachine** [comment]
Primarily repair orders, have not tested other. They worked in previous versions without canceling. Bots were perfectly able to do repairs inside beacon station and return with orders still active.
Also bots now respond negatively when given orders when they are idling at outpost, but order persists in this case.

**Comment by BlackMoons** [comment]
Can confirm I used repair-order bots a lot on beacon stations, really was a time saver to just move a bot over, clear enemies, tell them to repair and then switch to another bot so I could bring over the fuel rod I forgot, again.

**Comment by pavel4win** [comment]
I agree with the problem. Now, after the bot returns to the ship, you have to give him orders again. I also noticed this problem. Such orders as defend, extinguish fire, repair, after the bot leaves the uboat, become inactive and have to be refreshed. In previous versions, orders remained active and the bot began to carry them out upon returning to the boat, and this was convenient.

**Comment by Arctomachine** [comment]
From reading recent patch notes, I suppose this fix has not been included yet?

**Comment by itchyOwl** [comment]
No, it should be in the next update, released in the summer.
