### ISSUE TITLE
NPC Personality Traits Not Synced in Multiplayer

### ISSUE THREAD

**Issue by RubbingMyAxe** [FakeFishGames/Barotrauma#12989]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Probably a low priority issue for you, since you don't use traits for anything but dialogue, but in Multiplayer it looks like the clients just get random traits for NPCs instead of getting them from the server.

The culprit seems to be Line 577 in BarotraumaClient/ClientSource/Characters/CharacterInfo.cs

The client is just calling ch.SetPersonalityTrait(); which gets a random one instead of getting the information from the server.

I was using traits as part of my mod, and noticed that in Multiplayer they did not behave the way they should have. I would have NPC's that said they were Professional on the crew list saying lines as if they were Crazy. So I made the server print the NPC's trait and noticed that it was different from the one I am seeing client-side, some examples:

![image](https://github.com/Regalis11/Barotrauma/assets/72940553/9042ea78-e1ec-4bfc-be83-658f323068db)
![image](https://github.com/Regalis11/Barotrauma/assets/72940553/f636238e-28cc-4bf7-8a00-3a7bc615e606)
![image](https://github.com/Regalis11/Barotrauma/assets/72940553/33d9f654-2122-4078-a0d3-54898facef7d)
![image](https://github.com/Regalis11/Barotrauma/assets/72940553/dd81e992-3667-42f2-ba35-235535d53d11)

### Reproduction steps

1. Start a multiplayer campaign.
2. Check an NPC's trait on the crew list.
3. Check what the server reports the NPC's trait as.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

> The client is just calling ch.SetPersonalityTrait(); which gets a random one instead of getting the information from the server.

SetPersonalityTrait was the problem, but not for the reason you suspected: if you look inside the method, it chooses the random trait using the name and the tags of the character's head (e.g. female, head14) as the seed for the random selection, so it should always pick the same trait for the specific character. There was one issue there though, the tags weren't in a consistent order, which sometimes caused the seed to differ client-side. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d6f3a823942a797a4d15d9582d5bbcdd6920448a
