### ISSUE TITLE
Game becoming unplayable after a moment due to frames becoming non existent. Bug continues even after disabling barotrauma

### ISSUE THREAD

**Issue by Amliko** [FakeFishGames/Barotrauma#13096]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The bug started somewhere around 4-5 days ago( Wednesday or Tuesday) The first few minutes the game works fine with no issues, but after that it becomes a slideshow. I get 1 frame every 10 seconds, while sound works fine. My mouse teleports across the screen and it looks as if my FPS died. Bigger problem is, this continues even after barotrauma is turned off, while in that state I tried seeing if it was a CPU, GPU or other issue causing it problems but the usage of the pc components was as low as 20% at that time. Only way to fix it is to turn off the pc via the power button, as anything else is unresponsive due to the loss of frames and slowdown my pc suffers.

Barotrauma is the only game that it happens on, i tested it with games way more intensive (rust, War thunder) and games that have similar usage and none of them did anything to my pc. Verifying game files didn't fix it. Neither restarting the pc. Neither reinstalling my graphics drivers or updating them. I have tried reinstalling the game and disabling mods, but the bug still happens

### Reproduction steps

1. Turn on the game
2. After 1-10 minutes your screen should have 1 frame every 10 seconds, and anything aside from your sound will be slow and stuttery

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Happens in the menu of a self hosted server and in game of a dedicated server

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This sounds quite strange, I'm having a hard time thinking of how the game could be causing this kind of a slowdown after it's been shut down. Are you able to see if the barotrauma process is still running in the task manager? You mentioned you checked the CPU and GPU usage, but I wonder if it could have something to do with memory usage - do you see anything unusual in the "memory" tab of the task manager? How much memory does your PC have?

It could also be possible that your system runs out of memory when the game is running, and starts moving processes into virtual memory (which is very slow, and would most likely cause the system to stay slow for some time after the game has been shut down). In any case, I'm sorry for the inconvenience, and hope we can figure out where the issue is. :/

**Comment by Amliko** [comment]
I've tested it in singleplayer (not hosting a server) and played for an
hour fine. I've checked memory, and nothing appears out of the ordinary
during the bug either. Although, it was hard to see due to how slow
everything was

wt., 28 lis 2023, 19:04 użytkownik Joonas Rikkonen ***@***.***>
napisał:

**Comment by BlackMoons** [comment]
Try checking CPU/GPU temps when it occurs. If those get too high, your CPU/GPU will thermal throttle and everything will be slow even after quitting barotrauma.

**Comment by Amliko** [comment]
I did check, they didn't exceed 30-40°C

pon., 4 gru 2023, 06:28 użytkownik BlackMoons ***@***.***>
napisał:

**Comment by Regalis11** [comment]
No known steps to repro. Since it seems like this is not a widespread issue, this could potentially have something to do with the hardware, drivers, or some other factor at the player's end we unfortunately might not be able to diagnose without further info. :/
