### ISSUE TITLE
[Unstable] escort1huskcult reviving cultists and too hard to complete

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#13103]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Two issues:
1. A Husk cultist who had turned due to this:
```
      <Character from="outpostnpcs1" identifier="huskcultist">
        <StatusEffect target="Character" delay="60">
          <Affliction identifier="huskinfection" probability="0.1" strength="1" />
        </StatusEffect>
        <StatusEffect target="Character" delay="300">
          <Affliction identifier="huskinfection" probability="0.15" strength="1" />
        </StatusEffect>
        <StatusEffect target="Character" delay="600">
          <Affliction identifier="huskinfection" probability="0.2" strength="1" />
        </StatusEffect>
      </Character>
```
Couldn't seem to be killed. We killed the same NPC over 5 times and they kept getting back up within a minute. Disposing of them in the airlock seemed to be the only solution.

2. It guarantees that eventually every husk cultist turns, and it feels like this is way too soon. The reward (1500mk) and the risk/difficulty are way off.

### Reproduction steps

1. Multiplayer campaign
2. Take a Husk Cultist Transport mission and some other mission (or beacon station)
3. Note there's no way to do any 'stopping' mission, even when going straight for the level end, there's too little time before cultists transport
4. Kill husk cultists that turn, notice how they keep getting back up
5. Note also how 1500Mk isn't worth it at all 

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
Earn 1500mk, waste 3-5 Calyxanide (510mk each), stonks.jpg

But if you have 5 zealot robes then it becomes ez husk rep mission

**Comment by Regalis11** [comment]
> The probability keeps triggering every frame after a delay, rather than just once, if I understand it right?

It should only trigger once, if it triggers multiple times that sounds like a bug.

My intention when implementing this mission was that your goal is to make sure the escortees don't get huskified (with meds or e.g. items like the zealot robes). Although, I agree it probably needs some rethinking.

**Comment by JeroonBosch** [comment]
> Are you sure you actually killed them, as opposed to just making them go unconscious?

We didn't get to access the health interface, but we shot the cultist-turned-husk to 0 HP and they managed to get back up 4 times with nobody applying any healing. Do husks have a way to stabilize themselves?

How are the chances calculated by the way? When we did the mission, two of the cultists turned into a husk. Looking at the probability of 
```
probability="0.1"
probability="0.15"
probability="0.2"
```
shouldn't there be a really low chance of that happening?

**Comment by Regalis11** [comment]
> How are the chances calculated by the way? When we did the mission, two of the cultists turned into a husk. Looking at the probability of

All of those effects apply to all of the cultists, so basically it rolls the dice at 1 minute, 5 minutes and 10 minutes. There was a bug that caused the first effect to be applied twice (should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c82c94f), which made the probability a little higher though. If my math serves me right, the probability for any individual NPC to turn should've been ~45% when taking that bug into account. So I guess it could be that all of them turning was just bad luck?

**Comment by Vykn** [comment]
I would like to add that (even if this isn't a massive issue) the use of broad spectrum antibiotics to treat the escort cultists is basically prohibited because of the way the game treats responsibility for injuries. Even if the husk cultists have the husk infection, even if morphine is used to heal them directly after, if they are injected with abx, the player will lose reputation, forcing the use of expensive calyxanide. It is somewhat annoying that resources are unnecessarily spent only because npcs don't understand that some medicines have side effects, or frustrating because you don't have any calxyanide, and you have to deliberately let them die because saving them with abx costs reputation.

Is this a major problem that needs to be fixed? Not really. But it's one of those "would be nice" things that would be appreciated by the players, and I just wanted to point it out here.
