### ISSUE TITLE
Sprite not found error in console log: sonarOverlay.png not found (Incorrect %ModDir% in an item variant)

### ISSUE THREAD

**Issue by nORbDragon** [FakeFishGames/Barotrauma#13302]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

A similar issue was previously mentioned in bug reports #9994 and #12337 

Sometimes `%ModDir%/...` will be replaced by `Content/ContentPackages/...` and cause error in console, not always.

Mod just changes texture for navigation terminal screen. Nothing serious.

`command.xml` in mod have strings like:
`<ScreenOverlay texture="%ModDir%/Items/Command/sonarOverlay.png" origin="0.5,0.5" />`

Archive with mod - [3136460675.zip](https://github.com/Regalis11/Barotrauma/files/13925244/3136460675.zip)

### Reproduction steps

1. Install mod
2. Play game
3. Start new round (dock/undock)
4. Occasionally catch an error in the console

`Sprite 'Content/ContentPackages/Items/Command/sonarOverlay.png' not found`

<img width="1399" alt="20240113-baro-error" src="https://github.com/Regalis11/Barotrauma/assets/97672704/5ed72f79-d245-4196-9255-96173eaa8f2c">

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Finally managed to properly look into this. It seems the issue happens consistently with wrecked nav terminals (which this mod doesn't modify). The reason why this is happens is that the wrecked nav terminal inherits the sprite from the normal nav terminal, and when this mod overrides that, the sprite path of the wrecked nav terminal ends up being `%ModDir%/Items/Command/sonarOverlay.png`. But since the wrecked nav terminal is in the vanilla package, the game erroneusly assumes `%ModDir%` should be replaced with the vanilla package's path, leading to the non-existent `Content/ContentPackages/Items/Command/sonarOverlay.png` file path.

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5411/commits/b5ea01076e0a14292213e134d1677acaa3e71d7a

**Comment by Regalis11** [comment]
Merged to our private repo, fix coming up in a future update

**Comment by A2ur3** [comment]
it seems that character variants still have this issue
