### ISSUE TITLE
Getting arrested with stolen items on Station level load

### ISSUE THREAD

**Issue by BriannaTheBrave** [FakeFishGames/Barotrauma#13334]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If I have stolen items from a station (I am returning to a station I stole items in) I am already being arrested when the game loads in. This prevents any ability to take action, like evading to guards, getting rid of stolen items on the sub, etc. Playing singleplayer the AI crew members will get searched and arrested before I load into the level.

Could we either spawn on the sub when docking or have AI crew members not be searchable?

### Reproduction steps

Go to station A
Steal and item
Go to Station B
Return to station A with stolen item on your person
If a guard spawns next to where you spawn on the station, you're already being attacked when you load in.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I ended up addressing this by making the security not do any inspections in the first 30 seconds of the round (commit in our private repo https://github.com/FakeFishGames/Barotrauma-development/commit/2289015cd42264e0b3ed8ebba00f0e2a85371620). 

>Could we either spawn on the sub when docking or have AI crew members not be searchable?

In my opinion these options would cause other problems: it feels a little overkill to me to make the players spawn in the sub (and have to climb all the way up to the outpost) just to prevent this kind of a rare situations, and we can't make the security not inspect AI crew, because that'd be easy to abuse (you could just put the items in the bots' inventories or switch characters to avoid inspections).

**Comment by TerminatorTM** [comment]
Actually the load time for a client (not server) usually much more than 30 seconds (more like 60+-).

P.S. I know this is not the place for a discussion, but usually it is more comfortable to spawn in the sub (ideally in place there the player was before docking). Usually player need to finish some tasks he was doing, take (or put) something to\\from invertory before go and e.t.c. or even not go to station alltogether. The result is the player usually have to do double job (return to sub first from station and only after it - go to station if he need it).

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
