### ISSUE TITLE
PUCS, Alot of PUCS

### ISSUE THREAD

**Issue by EebleSheembl** [FakeFishGames/Barotrauma#13352]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image_2024-01-26_181248839](https://github.com/FakeFishGames/Barotrauma/assets/152429881/c2692400-1236-4b35-bd32-c0aed06ab25f)

### Reproduction steps

i bought three PUCS from one outpost that only sells three and i got alot more than three (Edited part) IIRC i bought one PUCS for myself and then sent the other two to the sub

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid couldn't find a way to reproduce this. Purchased 3 PUCS at a colony, and 3 spawned as expected. So this most likely requires some more specific circumstances to occur, but I unfortunately couldn't yet figure out what those could be.

**Comment by Jasontti** [comment]
Could not reproduce this either after multiple times

**Comment by Gravityowl** [comment]
I think I may have encountered a similar bug, if not the same one. I was at a merchant and tried buy some Ethanol and ending up getting about 76ish or so IIRC I have the logs the the campaign and they were truly confusing. The game whilst registering the initial purchase and buying the ethanol to send to the ship next round, continued to automatically buy additional ethanol while increasing the amount and cost each time did it. At the time we had a little over 20k marks IIRC and three people were using the shop at the same time that might have been the issue but I'm uncertain. The bug spent all of the marks in the bank. The issue seems to start around this timestamp in the log provided. 
[01/27/2024 01:46:28]

[Death Taxes & Chaos_2024-01-27_0151.txt](https://github.com/FakeFishGames/Barotrauma/files/14234779/Death.Taxes.Chaos_2024-01-27_0151.txt)

**Comment by EebleSheembl** [comment]
I bought one for myself and then sent the other two to sub iirc
