### ISSUE TITLE
[Unstable] Sounds from StatusEffect don't stop playing even after source is removed

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13357]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sounds generated by statuseffect don't stop playing even after source is removed

See: 
```xml
  <Item name="ballastfloratoxins" identifier="ballastfloratoxins" Scale="1" tags="" sonarsize="0" hideinmenus="true" health="10" depth="0.1" isdangerous="true">
    <Sprite texture="Content/Items/Weapons/weapons_new.png" sourcerect="0,0,2,2" depth="0.55" origin="0.5,0.5" />
    <ItemComponent>
      <StatusEffect type="Always" target="This" condition="-1">
        <ParticleEmitter particle="toxins" particlespersecond="1" scalemin="0.2" scalemax="0.3" anglemin="0" anglemax="360" />
        <sound file="Content/Items/Alien/AlienPump.ogg" range="500.0" loop="true" />
      </StatusEffect>
```

Looping issue?

### Reproduction steps

1. use `spawnitem ballastfloratoxins cursor` (in water to see the particles)
2. wait 10 seconds
3. sound still plays

_No response_

### Version

Unstable

**Comment by Regalis11** [comment]
Thank you for the report! Did this actually happen in the stable version of the game? I was only able to repro it in the unstable version, and found a recent change that seemed to have caused it, but that change is only included in the unstable build atm.

Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/fe22e6157227acdd9ae6cefbb38965281c77e6f9?

**Comment by ubertpendragon** [comment]
oh yes unstable sorry

**Comment by NilanthAnimosus** [comment]
Closing as it has been merged, and will be in the next patch.
