### ISSUE TITLE
General ticket about audio device issues

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13430]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Since we have several tickets about similar/identical audio issues on different kinds of audio devices, we decided to create one catch-all ticket about them to have all the information easily available in one place.

The game doesn't recognize certain kinds of (USB?) headsets:
- [No audio output over usb headset](https://github.com/FakeFishGames/Barotrauma/issues/3865)
- [GSP 670 Headset causes 'suitable capture device not found error'](https://github.com/FakeFishGames/Barotrauma/issues/3625)
- [Game doesn't recognize correct audio output device](https://github.com/FakeFishGames/Barotrauma/issues/12877)

No audio devices listed (potentially the same issue or related to the issues above?):
- [No audio input devices available](https://github.com/FakeFishGames/Barotrauma/issues/9817). **Potential workaround listed in the ticket, needs further investigation**.
- [No audio devices showing up on device list](https://github.com/FakeFishGames/Barotrauma/issues/13373)

Other:
- [Audio device doesn't automatically switch when connecting headphones](https://github.com/FakeFishGames/Barotrauma/issues/7081)

### Reproduction steps

-

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Noticed today with my new wireless bluetooth headset that whenever my headset lost power by being inactive too long the game would throw an error. Same happens if I just turn the headset off while playing. 

I think the issue is mostly caused because we aren't actively checking for "new" devices while the game is already running, selecting the default device whenever its available would be one way to try and circumvent this. 

![image](https://github.com/FakeFishGames/Barotrauma/assets/7299826/8223789b-db26-4015-a90e-a6ebf9b9c15b)
