### ISSUE TITLE
Limb limit on joint not working (spritesheet orientation incorrect)

### ISSUE THREAD

**Issue by AzureNocte** [FakeFishGames/Barotrauma#13457]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I was working on a modded creature, in the beginning everything went well, but out of some reasons, the limb limit on joint 0-1(head to neck) seems not working anymore, cause the creature's head to "split"...
I tried many ways to fix this, but none of them worked. I suspect it is a bug?

here are the files:
[Caveeel.zip](https://github.com/FakeFishGames/Barotrauma/files/14360614/Caveeel.zip)

### Reproduction steps

1.install the files
2.enter character editor
3.make it swim, and observe

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I don't actually see any issues with the joint limits, they seem to be correctly restricting the rotation of the head-to-neck joint to what they're set to.

I believe the issue here is the spritesheet orientation, which determines which way is considered "forwards" on the spritesheet. It's configured to point up, even though the limbs are set up pointing from left to right, causing it to behave strangely when the character flips around. It also seems the character is set to mirror horizontally when wants to head in a different direction, which is probably not a good idea with a snake-like character like this.

The spritesheet orientation isn't explained at all in the editor so it's no wonder you missed it - we've clearly got a lot more work to do to get the editor to be a bit more user-friendly.

**Comment by Regalis11** [comment]
We'll be adding some more instructions to the editor (and expanding the modding documentation to properly explain the meaning of the orientation), so we'll keep this report open for now until that's done. Commit in our private repo: https://github.com/FakeFishGames/Barotrauma-development/commit/bdbeb606c73a2d0d6324d4d07dd0092312fcca12

**Comment by AzureNocte** [comment]
That's real quick! So this is related to sprite orientation, I never considered that... So spritesheetorientation="0" means to point up, I changed its value to 90, it should be point rightward. And I agree what you said, mirror horizontally for snake-like creatures seems weird.
Thanks a lot!!! Upgrading to editor would be great news for us modders!
