### ISSUE TITLE
When spawned with commands, Security Officers cannot open Secure Steel Cabinets and Medical Officers cannot open Toxin Cabinets

### ISSUE THREAD

**Issue by MarkCringan** [FakeFishGames/Barotrauma#13478]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue feels incredibly niche but I thought it still was worth mentioning:

Whilst playing in the submarine editor test mode, the single player campaign, or a multiplayer sandbox mission Security Officers spawned with commands cannot open Secure Steel Cabinets and Medical Officers spawned with commands cannot open Toxin Cabinets. Captains spawned with commands do not have universal access either. 

### Reproduction steps

1. Start the submarine editor or a single player campaign.
2. Enable cheats.
3. Use commands to spawn in a Security Officer, Medical Doctor, or Captain.
4. Spawned Security Officers cannot open Secure Steel Cabinets (or open security-only doors) and Spawned Medical Officers cannot open Toxin Cabinets.
5. Captains spawned with commands have no special access either. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Single player, Multiplayer Sandbox Mission, Submarine Editor Quickplay

### Version

v1.2.12.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Bill-E-Furd** [comment]
I know this is a dead thread, but did they spawn without items? If so, it's the fact they don't have an ID, since it is the ID and not the role that allows access. Even if they do have an ID, it might not have the proper tags. I found this out by accident back when the Orca 2's toxin cabinet used to have the wrong tag, denying access to doctors hired before the ship was purchased. You can probably verify this in sub editor by checking the tags required by the doors/cabinets you are trying to access.

**Comment by Regalis11** [comment]
We've actually fixed this in our private repo (commit: https://github.com/FakeFishGames/Barotrauma-development/commit/246b3fae69ca03118ccaf9336f8d14dbf6e73ae3), I'd just forgotten to comment on the report. :) The issue was that characters spawned via console commands simply weren't given the ID card tags for the sub they spawn in at all.

**Comment by Regalis11** [comment]
Fix coming up in the next unstable build
