### ISSUE TITLE
deconstructionspeed doens't seem to be working

### ISSUE THREAD

**Issue by exheres** [FakeFishGames/Barotrauma#13513]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

setting any value for the attribute deconstructionspeed doesn't seem to change the speed of the deconstructor ingame

### Reproduction steps

a

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I could not reproduce this. Tested by adding two deconstructors on a sub, and setting the deconstruction speed of the 2nd one to 5. It seems to deconstruct 5 times faster, as expected.

**Comment by exheres** [comment]
i tried to update it in an xml file like example below and it wouldn't change, sorry i should've made it more clear 

<Deconstructor canbeselected="true" powerconsumption="500.0" msg="ItemMsgInteractSelect" DeconstructionSpeed="10.0">

**Comment by exheres** [comment]
<Deconstructor canbeselected="true" powerconsumption="500.0" msg="ItemMsgInteractSelect" DeconstructionSpeed="10.0">

**Comment by Regalis11** [comment]
I'm afraid I still could not reproduce the issue. :/ Tested by changing the vanilla deconstructor the same way as in your xml example, placing one in the sub editor, and then giving it a test in the editor's test mode. The deconstruction speed seems to be set to 10, and it seems to deconstruct at x10 speed.

**Comment by exheres** [comment]
without replacing the deconstructor it doesn't update the value, unlike Fabricationspeed which does seem to update the value on fabricators already placed

**Comment by Regalis11** [comment]
Thanks for the clarification! This actually seems somewhat intentional: this setting was intended as a way to modify the speed on a per-sub basis, or to create custom items with a non-default speed, not as a way for mods to modify the speed of vanilla deconstructors already placed in existing subs. That's why it and always uses the values set in the submarine file (which defaults to the value in the item xml), not the ones in the prefab.

This is somewhat of a hacky workaround, but if you want to force it to 10 in all existing subs, you could use an `<Upgrade>` element, which automatically changes the values in all existing devices if the sub has been saved in a version prior to the specified version number:
```
<Deconstructor canbeselected="true" powerconsumption="500.0" msg="ItemMsgInteractSelect" DeconstructionSpeed="10.0">
   <Upgrade gameversion="1000.0.0.0" DeconstructionSpeed="10.0"/>
</Deconstructor>
```

It seems the behavior of the fabricator is different because in prior versions it had not been saved in the submarine file.

I'm sorry for the inconvenience, I hope you can get this working with the above workaround!

**Comment by exheres** [comment]
oh i thought it was unintended behaviour so i reported it, my apologies, i'm already using an upgrade element that somebody from your discord told me to use, sorry for wasting your time

**Comment by SomeRandomNoobKekeke** [comment]
Just note that there's a [mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2548565390) that also changes deconstuction speed
But achieves this by overriding sub upgrades that you then can buy
