### ISSUE TITLE
[Feature Request] Change Vending Machine Item Price + Items

### ISSUE THREAD

**Issue by brand175** [FakeFishGames/Barotrauma#13516]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I am trying to make a ship that has a vending machine inside. It would be nice if I can limit how much stock is available and change the price accordingly. An option to stock the vending machine or auto fill after each outpost/base would also be needed.

### Reproduction steps

Misc.

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
It's very hard to do because what is sold from vending machine is not defined in one place
Instead it's all defined in individual items in Fabricate component with suitablefabricators="vendingmachine"
So to change it you need to override every item in the game
And you can't autofill because it's not a merchant in a box, it's just a fabricator, i doesn't have any internal state
And same with items spawned in cabinets on a sub, or in wrecks, or in outposts, they are not defined in cabinets nor separately in their own content type files, all this info stored in items themselves and is unmodable until the great refactor

**Comment by Regalis11** [comment]
The issue tracker is for bug reports, please post feature requests [in the discussions](https://github.com/FakeFishGames/Barotrauma/discussions/categories/ideas-and-suggestions) instead. :)
