### ISSUE TITLE
[Unstable] Jovian radiation is still opt-in by default

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13510]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Jovian radiation is still an optional setting for game difficulty, even though it's canon in the lore (scientist NPC in the end level), and it is from my understand the "intended" setting.

We have several new difficulty modifiers such as "patdown chance" but radiation is still off by default on Hard and Abyssal
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/f054d08b-5d37-4d12-b408-1a1e7f756acb)

By having it off by default new players will not experience the game with radiation on and the game gives the message that radiation is not intended or a challenge mode that isnt even part of the highest difficulty

**Comment by Regalis11** [comment]
This is intentional. The radiation didn't turn out to work as a gameplay mechanic as well as we'd hoped, so we made it be off by default.

> even though it's canon in the lore (scientist NPC in the end level)

In my opinion there's not that much of a discrepancy here. According to the lore, the radiation is becoming more intense, but this doesn't necessarily mean that it's so intense or increasing in intensity so fast that it'd have an immediately noticeable effect in-game. Perhaps it just means your crew is very likely to get cancer a few years from now, and that in a couple of years it's going to start causing more immediately obvious health problems in the higher-up biomes.
