### ISSUE TITLE
CPR deals blunt damage due to impact tolerance

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13521]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you CPR someone on the floor, the animation pushes the ragdoll against the floor dealing blunt damage.

Increase impact tolerance during CPR?

### Reproduction steps

CPR someone on the floor with either 0 or 100 medical skill and it will happen

Do it underwater where there are no hard surfaces

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
> Increase impact tolerance during CPR?

inb4 bug report about impact damage not working during CPR (very clear exploit that can be used to protect characters from impacts :))

**Comment by Regalis11** [comment]
I'm afraid I could not find a way to reproduce this:
https://github.com/FakeFishGames/Barotrauma/assets/14351070/ec22e8cb-8d05-4bef-b2cd-38d09ee64256

**Comment by ubertpendragon** [comment]
Just drag the patient around a bit because it definitely happens

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/ba2639f0-26de-415e-a453-d7df554d2263)

It's more pronounced on unstable because opiates are much worse at bringing people out of critical

**Comment by Regalis11** [comment]
Managed to get it to happen now! It seems to require the characters to be in some specific pose, and seems to be hard to get it to happen reliably. In my opinion this is a very low-prio issue though, the amount of damage is minuscule and I think it could even be considered a feature that CPR has a small chance of causing minor damage (it does in real life too).

**Comment by ubertpendragon** [comment]
https://cdn.discordapp.com/attachments/668819422919524352/1217084136364179486/Barotrauma_2024-03-12_23-16-36.mp4?ex=6602bcee&is=65f047ee&hm=c0e3833626004835c9864d0ba62b42a2c7e3c986a3fd4254ac6ba4d680bffe68&

having two people cpr at the same time absolutely destroys all the patient's bones

**Comment by Vykn** [comment]
The damage can get really bad.

https://github.com/FakeFishGames/Barotrauma/assets/37850646/f0b98199-dc10-48c5-a9b2-59ecd5427333

This is especially pronounced in the new unstable version, because reviving patients is a lot slower. It has always occurred, it's just that we only noticed it in unstable testing because opiates are weaker and cause more oxygen low, and so it's a lot more likely that a second medic may join in cpr.

Organ damage already exists to punish use of cpr when low skilled. Having multiple fully trained medics doing cpr together should not break all the bones in a patient's body.

**Comment by Regalis11** [comment]
> so it's a lot more likely that a second medic may join in cpr.

Tbh two people doing cpr at the same time seems like a very bad idea, and something that should cause damage. :D

**Comment by Vykn** [comment]
> two people doing cpr at the same time seems like a very bad idea

Then that should be made explicitly clear to the player, or prohibited altogether.

But I don't see why e.g. one rescuer couldn't perform compressions while the other gives breaths. That is a real technique.

The current behaviour is not fair to players.

**Comment by Regalis11** [comment]
> Then that should be made explicitly clear to the player, or prohibited altogether.

Hmm, I think my perspective could be skewed here, but to me it seems clear enough from the damage the character takes when you're doing this. If the characters were taking turns compressing and giving breaths, it would make sense, but here they're pounding on the character's chest at the same time which results in the forces being high enough to cause injuries.

**Comment by Vykn** [comment]
I don't think it's reasonable to expect players to notice and understand that somehow two people doing CPR would start doing crazy amounts of damage when a single medic doesn't. It's a videogame - players suspend their disbelief of morphine healing gunshot wounds, and they equally won't try to apply real logic to wondering about the logistics of multiple medics doing CPR to the one patient. CPR heals oxygenlow, so more CPR heals more oxygenlow.
Players don't pay attention to every single affliction that a patient has, especially when they have a bunch of different injuries all across their body, and nowhere in the mechanics of CPR is blunt force trauma specified.
The example given above makes it incredibly clear what's occurring, but it's not a good example because that's not what real patients' injuries look like. Downed players are very likely to have a variety of injuries spread across all limbs, and a small amount of blunt force trauma applied to each limb randomly every few compressions is likely to go unnoticed for a long while, *especially* since it only happens sometimes.

Baro has a bad reputation for having incredibly opaque mechanics, and while this is super easy to avoid if you know about it, I see this being a thing that players won't learn about unless doing a lot of experimentation or just being told about it by another player, and until that happens there's going to be frustration. 

I personally think the best option would be just to fix the force issue. It's a videogame. It doesn't need to be super realistic, and I like that multiple medics can work together to treat a patient. But, just removing the ability for multiple people to do CPR would also neatly fix the issue. I don't think the current behaviour is okay because if it makes sense that multiple people doing CPR would cause a lot of damage, then it should always happen, and not randomly occur depending on the position of the ragdoll of the patient.

**Comment by Regalis11** [comment]
Yeah, those are good points. I'm not saying this should be kept for the sake of realism, my reasoning is just that this seems like a very minor issue due to the minuscule amounts of damage it causes, and that it only starts doing meaningful amounts of damage if multiple people try to do CPR. 

I honestly didn't expect it to be common for multiple people to do CPR at the same time (doing that had never occurred to me personally), and I would've assumed it to be clear that when you're doing something this odd, having multiple characters violently pound on the ragdoll, it wouldn't be hard to realize why the character is taking damage.

But my perspective is often very distorted after working on the game for so long, and I'm often very wrong about what the average player might find clear and what they don't, so I suppose we could address this if it really is common for multiple people to do CPR at the same time.

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/pull/5059/commits/f79407bef17b46fd9ad6d23831898fd12cae5836

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5059/commits/f79407bef17b46fd9ad6d23831898fd12cae5836

Tested in SP and MP with multiple clients performing CPR
Tested also doing CPR inside and outside of the sub

No issues found
Closing ticket
