### ISSUE TITLE
[Unstable] Some vanilla wrecks got hulls in open breach areas

### ISSUE THREAD

**Issue by PanmanS** [FakeFishGames/Barotrauma#13524]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While it is not a bug, I find it weird there are wrecks using hulls in open breach areas, thus making it look extremely ugly upon shining and vanilla submarine gunlight into hole of wreck.

It would be nice if all other wrecks with such breaches got same treatment, including but not limiting to Typhon 2, Remora and many others.

This is what it should look like (and btw THANKS TO WHOEVER REMOVED HULLS IN MEDBAY):
![Barotrauma_NXDTtV4TqH](https://github.com/FakeFishGames/Barotrauma/assets/42521948/4fdf73fa-d9ed-47bc-b6af-e96e1f5f9207)

And this is rather upsetting display of how not to do it:
![Barotrauma_x2RQQp3QAS](https://github.com/FakeFishGames/Barotrauma/assets/42521948/a14ff54e-c91a-4ac5-a653-9e9e1fc7c637)

### Reproduction steps

1. Shrimply open sub editor and start in any sub
2. F3, `spawnsub Camel_Wrecked false`, `lock`.
3. Shine a gun light into bottom breach area.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.13.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
What panman meant to say is:

Since subs use "draw behind sub" lights for performance reasons, the interaction with hulls can become quite ugly:
The light will shine in areas without a hull, and not in areas with a hull. 

You want to avoid hulling that has too much contact with the exterior like this:

A hard cut in lighting, the background is open/transparent but the light doesnt  shine
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/e2bca8dd-3e89-4b1a-9c64-4756ec91c560)
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/866d8640-a44b-4e90-a579-e8b0298e9612)

A very noticeable corner hull
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/db9e2b7e-2070-40f3-a070-decd8f1280e0)
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/5a71ee51-2fb0-44da-99d6-a33cb32d4e9e)
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/479307f3-c17b-4f9c-b375-6746a198095b)

Remora has many of those corners
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/f7be3bee-c226-4d59-b7c6-c1c050fb670e)
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/b23cba5a-97fe-4f5a-ba4c-131bfc82ee05)



The opposite is also true: 
Areas that are by all means "opaque" are unhulled:

Barsuk
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/8981858b-5080-466a-8ff9-4feae3f3c686)

Humpback
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/c670f55d-9c32-4086-8d24-5be92eb46438)

**Comment by HeatedWafflez** [comment]
With how good performance has gotten as of lately, especially with lighting, I would just insist that by default turret lights should not be drawn behind subs anymore and that they should cast shadows.

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5047/commits/02614cfdbebd3182871ed5927806aa2508063da0

Went through all of the wrecks, things look better and you can't see through walls like in the examples

There are some harsh transitions in places of wall lights and gunlight shining in.
This is a limitation with the engine currently
![image](https://github.com/FakeFishGames/Barotrauma/assets/8488224/f59822b4-3fcb-42bc-838a-89ed01752328)

Closing this as completed, hulls removed - no issues, but i'll make a new one for the light transition.
