### ISSUE TITLE
Some issues with Gap.outsideCollisionBlocker

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [FakeFishGames/Barotrauma#13525]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### disclaimer
Well, i'm not saying you must fix all of them this instant. I'll just put them here so you know. Imho it might even be easier to rework this outsideCollisionBlocking system entirely
I used [this](https://steamcommunity.com/sharedfiles/filedetails/?id=3174898162) for testing
I might have misunderstood how some of these things work
Videos are potato quality mostly because of github 10mb limit
### 1. There are many zones not covered by collision blockers on each sub

https://github.com/FakeFishGames/Barotrauma/assets/122838333/b60cfab7-c0fa-4c32-af6e-d23ced1d0dd8

another example

https://github.com/FakeFishGames/Barotrauma/assets/122838333/c6fb9af2-f68a-4252-be0a-d68945ffed55

They seems to be located where the ray from hullToOut gap is blocked by something
It could be second layer of walls, turrets, maybe depth charge tubes, maybe some fins

There's an easy way to see them:
lock sub, freecam, explode the sub, teleport it into a wall, wait a few seconds until all colliders settle, teleport it back into open water

First all colliders activate because they are in the wall and then in water every collider disables except for blocked ones because you just return without setting its state to false  [here](https://github.com/FakeFishGames/Barotrauma/blob/3b722fae594d298f7a3b9812adac7b9f991be2dd/Barotrauma/BarotraumaShared/SharedSource/Map/Gap.cs#L727)

[Here are screenshots of every sub](https://drive.google.com/drive/folders/1Emg5tTlz5BMgsHv6SFcz8W709Ei9DQPl?usp=drive_link), green zones are uncovered

### 2. Colliders are not disabled explicitly and remain active by default
This is not really a problem by itself but opens a gap for more problems
I suppose normally colliders are updated when somebody approaches the gap
And might remain active if the gap if left alone

https://github.com/FakeFishGames/Barotrauma/assets/122838333/558e15c2-fb1f-456f-936c-66b465f9e82f

### 3. Colliders that remain active seems to be blocking lasers and bullets

https://github.com/FakeFishGames/Barotrauma/assets/122838333/f835e58a-2fd3-43b8-8935-a8ee549b1f35

### 4. Sometimes you can enter submarine without triggering the gap

It works a least on the bottom of Orca 1, i don't really understand why, maybe because ballast hulls are not intersecting with outer walls

So you might touch colliders that remain active and doesn't want to update

https://github.com/FakeFishGames/Barotrauma/assets/122838333/3735f0e6-a14c-4d6a-932a-289d3bb7c3d2

### 5. Colliders spawn between main sub and its drone

https://github.com/FakeFishGames/Barotrauma/assets/122838333/e92bc1c9-7793-4d5c-bf8f-859967322f20

### 6. Colliders between main sub and pirates are annoying
Imagine pirates sank on your sub
All entrances blocked, subs stuck, you drilled a hole to them but you can't pass through it because of these pesky colliders, and there are not enough space between subs for you to be considered outside 

https://github.com/FakeFishGames/Barotrauma/assets/122838333/d6a8863b-40fc-48aa-bf4a-2fbae729fb06

### ~7. Closed hatches don't create colliders~
~It's kind of intended, but what if the hatch is deep inside the sub, or walls around it are broken? It will create a hole in colliders~

https://github.com/FakeFishGames/Barotrauma/assets/122838333/5eb3d811-bd6a-4988-98b9-af0b14c7a177

### Reproduction steps

Use [this](https://steamcommunity.com/sharedfiles/filedetails/?id=3174898162)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
I mean there are more ways to end up inside a wall:
If you try to leave the sub in uncovered zone you might accidentally swim into a wall and get stuck, some of that zones are too close to subs border
While you are repairing hull from outside, submarine may move and push you inside a wall
Creatures that are tryng to board the sub might get pushed into a wall as well

[People manage to swim into a wall from time to time](https://new.reddit.com/r/Barotrauma/comments/18aq9a2/_/)

If it's just for when you're leaving the sub then fine, who needs to repair outer hulls, care about tigerthreshers anyway?

> 2. Colliders are not disabled explicitly and remain active by default. Why is this a problem? 

Well it's not. But i would disable them just for safety. It would solve 3 and 4. Also as you can see in 1 if you somehow enable blocked collider it will remain active and blocking you inside sub forever (or until you fix its gap)

> 4. Sometimes you can enter submarine without triggering the gap
> Why should it trigger when entering the sub?

For the people that are fixing hulls from outside. But yes, you can just ask Artie to do that

> 7. Closed hatches don't create colliders. I don't see why they should.

Just for cases when your sub is falling on a thresher swarm, they naturally gather around hatches and often pushed into a wall like this. But who care about tigerthreshers anyway?

> Imho it might even be easier to rework this outsideCollisionBlocking system entirely. 

I think it works accceptable in vanilla, but [it doesn't work at all for larger creatures](https://github.com/FakeFishGames/Barotrauma/discussions/12680)

> It's not even intended to help creatures eat you

ye ok

> Do you have some kind of ideas on a better system?

I do, but i'll probably make a mod first and if it works fine then i make a PR

**Comment by Regalis11** [comment]
I think there's probably still some kind of a misunderstanding of what these do. They are only intended to stop you from colliding with things outside the submarine when you're exiting the sub, i.e. when you're still in the submarine's "local coordinate space" and cannot collide with things outside. I don't see why there'd be any need for them to affect characters outside the sub: they are already in the "external coordinate space" and collide normally with level walls and such. They don't collider with these blockers though, because the blockers are in the sub's local coordinate space.

To me it seems like the only clear issue with the blockers here is that projectiles can hit them, the others seem unrelated to the blockers / or misunderstandings of what they do or how they work.

**Comment by SomeRandomNoobKekeke** [comment]
I didn't mean that they need to affect characters outside. I meant cases when 99% of your body is ouside but you are touching some broken wall with your toe and considered inside

**Comment by Regalis11** [comment]
I still don't quite follow. You mentioned for example threshers getting pushed by closed hatches: unless I'm missing something, enabling the blockers on touch would not affect anything. The threshers wouldn't collide them because they're outside, and characters exiting the sub should collide with them either because you can't exit the sub through a closed hatch.

> Colliders are not disabled explicitly and remain active by default. Why is this a problem?

> Well it's not. But i would disable them just for safety. It would solve 3 and 4. 

Also, to continue on this: it would not solve 3 and 4. It would just make the issue occur in the situation where the blocker is active, e.g. that you couldn't fire the turret when someone is exiting the gap near it.

**Comment by SomeRandomNoobKekeke** [comment]
I mean if there are broken walls around the closed hatch, threshers are long, they can touch it and be consideren inside while hatch is closed and there's no collider against it
Yes, ok i wouldn't fix 3, but 4 seems to be caused by colliders being active when there's no reason to be

**Comment by Regalis11** [comment]
>I mean if there are broken walls around the closed hatch, threshers are long, they can touch it and be consideren inside while hatch is closed and there's no collider against it

Ah, I think I got it now! So you're thinking of a situation where at thresher is exiting the hatch, the hatch then closes, and the collider gets disabled even though the thresher is still considered to be inside? That does seem like an issue, although I don't think keeping the collider enabled would be an appropriate way to fix it. The same issue could happen if there was a solid wall in place of the hatch: the thresher could exit through a gap next to it, and wiggle to the position with no collider while still touching the sub, and end up inside a level wall.

This is not a trivial problem to solve, so if you do have ideas for a solution, I'd be very interested in hearing what you have in mind! I think a robust solution might be something like modifying the physics engine so a fixture can register collisions in both the sub's internal coordinate system and the external. That could possible be done by making it actually exist in two positions in the quad tree that stores the fixtures, or maybe by using some kind of a "proxy fixture" that registers the collisions in the "other" coordinate space.

**Comment by SomeRandomNoobKekeke** [comment]
No, i just thought of making them slightly more precise
Like Scanning cell in radius of length of the boarding creature and not in ray, make colliders exactly match outer edges of those cells, move them relative to the sub so they would stay in the same place in real world

> That could possibly be done by making it actually exist in two positions in the quad tree that stores the fixtures (and then adding some custom logic to handle the collisions in both coordinate spaces), or maybe by using some kind of a "proxy fixture" that registers the collisions in the "other" coordinate space.

i like your funny words magic man.jpg

Btw, how do you know all this? Do you have some secret farseer docs or did you just read all the souce code?
Their site seems to be dead, and docs in [archived version](https://web.archive.org/web/20120303145252/http://farseerphysics.codeplex.com/documentation) are very shalow and don't look like a docs
There's no words about quad trees or proxy fixtures
Should i just look in box2d docs and guess how it should work in c#?

**Comment by Regalis11** [comment]
> Like Scanning cells in radius of length of the boarding creature and not in ray, make colliders exactly match outer edges of those cells, move them relative to the sub so they would stay in the same place in real world

Something like that could work too, but I feel that'd easily get very complex: you'd most likely need to modify the shapes of the fixtures on the fly, and possibly use some more complex shapes than just lines to ensure they always cover anything. And even then, it might not be foolproof: each individual fixture might need to be arbitrarily large to ensure nothing can get past it, no matter how large the character is.

Worth noting though that they do already move relative to the sub, but the position is only refreshed periodically because doing the raycasts frequently would lead to performance issues (and the "scanning" and modifying the shape would most likely be much more expensive).

>Btw, how do you know all this?

I've gradually learned it by just using it, reading through the code and messing around with it (we've e.g. done quite a bit of modifications and optimizations to it during the development). The code is pretty well documented and easy to read. And since it's a fork of box2D, the box2D docs are also very useful: practically everything in there applies directly to Farseer too, even though the syntax of the code examples is slightly different. For example, it explains what fixtures and "trees" are in this context, both of which you'd probably need to understand if you wanted to lets say modify the shapes of the colliders to match the edges of the cells.

**Comment by Regalis11** [comment]
As discussed above, the issues listed here are for the most part theoretical, and the actual noticable issues they cause seem to be rare and minor enough that I don't think it's worth it to rework the "blocker" system at this point to address them.
