### ISSUE TITLE
Bots leave diving suits at the station, and then if you save and exit, the suits are irretrievably lost.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13669]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13652

<div type='discussions-op-text'>

<sup>Originally posted by **pavel4win** March 22, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots leave diving suits at the station, and then if you save and exit, the suits are irretrievably lost.

### Reproduction steps

If the bot was wearing a diving suit when docking, bot wears off the suit at the station immediately after dock. If you save the game after this, the suit is lost.
One day I lost all my suits at once.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by BlackMoons** [comment]
A little more control over when AI drop suits would be great.. Or just have them a little more likely to keep them on in an emergency...

Iv got a drone that is a constant source of AI's running into the drone to fix a leak, then dropping their suit off in the drone instead of in the suit locker 10 feet away... 

Maybe a solution would be some logic like: "Only put away suits in nearest unoccupied suit locker (or locker you got suit from?), Don't put away suit if next job is closer then suit locker and/or high pressure zones still exist on submarine"

**Comment by itchyOwl** [comment]
> Iv got a drone that is a constant source of AI's running into the drone to fix a leak, then dropping their suit off in the drone instead of in the suit locker 10 feet away...

The bots should only drop the suits if they have something of higher prio to do, like an active order. In the idle state, the bots should carry the suit to a nearest locker. Also, they shouldn't drop the suits in airlocks or ballast (but they seem to do that).

Dropping the suits in the airlocks (automatically created when two docking ports are created is a bug, which should now be fixed in FakeFishGames/Barotrauma-development#5173.

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5090/commits/3a1b0f9d0ec33e5178b88afdf87363ab0b5e420f

Tested in SP and MP
Tested with bots dropping different items when doing level transition and saving and quitting 

All items that non player character dropped while being in outpost were returned to the sub properly

No issues found
Closing ticket

**Comment by BlackMoons** [comment]
Just a thought, but when you close a ticket, could you please mention if you actually fixed/changed something, and what? 

Many times a ticket is closed with 'tested, no issues found, closing ticket'. To others this reads as 'Bug not found, report is invalid, closing ticket' since there is no mention of what was changed, if anything, or if the issue was ever addressed.

**Comment by Regalis11** [comment]
@BlackMoons We generally always comment on the ticket when we fix the issue, but we also often forget to do that - which happened in this case too. But in general, if you see a comment saying something like "tested, no issues found" it means we've implemented some kind of a fix and tested it internally.

This issue was fixed in commit https://github.com/FakeFishGames/Barotrauma-development/commit/ea8623319f60b9f574b64a26c11274ed045d1ce3 (private repo):

> Fixed items that are marked for "relocation" (automatically moved to the main sub) after a bot drops them in the outpost disappearing if you save and quit. Now we also handle the relocation when saving and quitting mid-round, not just when starting a new round.

**Comment by pavel4win** [comment]
Looks like I've found another case where a diving suit disappears. 
https://github.com/FakeFishGames/Barotrauma/discussions/14112
