### ISSUE TITLE
Circuit box xml sometimes has incorrect usedresource for components

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14392]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14388

<div type='discussions-op-text'>

<sup>Originally posted by **Max112358** August  2, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I created the mod Blueprints on the steam workshop. It saves and loads circuitboxes based on their XML data. 

Sometimes circuitboxes XML data will change from the base resource used to input each component (such as "memorycomponent" into "fpgacircuit". This messes my Blueprints mod up because that's the info I use to rebuild the circuit. 

This only happens sometimes and I'm not sure what causes it. Even more confusingly I've seen circuitboxes in the wild on multiplayer that have only some components this happened to.

This is a link to the mod if you want it for testing purposes.
https://steamcommunity.com/sharedfiles/filedetails/?id=3301014847

[absurdly_complex_reactor.txt](https://github.com/user-attachments/files/16463829/absurdly_complex_reactor.txt)
[default_docking_hatch.txt](https://github.com/user-attachments/files/16463830/default_docking_hatch.txt)

![xml_bug](https://github.com/user-attachments/assets/6695456c-86f5-49b8-816f-af79ddde0406)

### Reproduction steps

Start a multiplayer campaign.
Make a circuit box. Attach it to a wall and make a circuit inside it.
Observe the XML data of the box. You can get this via the item.save() function built into items.
BreadcrumbsBarotrauma/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs
You can get it easily by using my Blueprints mod and just saving the circuitbox to a file (all it does is run this function)
See that the circuitbox is normal.
Play the game for a while.
Check again, the XML has changed to have the "fpgacircuit".

If you just want to see one, the dugong docking hatch box seems to have this bug from the start of the game.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No errors or crash reports.
```
</div>

**Comment by Max112358** [comment]
I screwed this bug report up. I had a flawed understanding of how the circuitbox system worked. It turns out this is what happens when you use a fpgacircuit to place components instead of the actual components. Sorry about that.

With that being said, I would humbly request that the XML somewhere contains what kind of components the circuitbox holds, just so it can be recreated later.

Something like:
<Component id="6" position="1119.8271,1105.6787" backingitemid="6,0" usedresource="fpgacircuit" item="multiplycomponent" /> 

Basically just add the item to the component section.

Also as long as I'm asking for stuff, it would be great if there was a function to make IReadOnlyCollection out of a CircuitBoxNode. So just take a circuitboxnode as a parameter, and return an IReadOnlyCollection of that node. Probably more generic than that though, so any element and make an IReadOnlyCollection out of it. 

I need to be able to create IReadOnlyCollection in order to manipulate functions like MoveComponent located at:
Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Signal/CircuitBox.cs

**Comment by Regalis11** [comment]
Closing, since the initial bug report seemed to be a misunderstanding of what "usedresource" is, and it's actually behaving as intended.
