### ISSUE TITLE
Thalamus brain suicide by lack of water

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14544]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14498

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** August 25, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On some wrecks, broken/open ducts let water flow drain to rooms below and the thalamus dies to a lack of water

There's honestly no reason for thalamus *structures* (not leucocytes) to be taking damage when not in water because it just makes organs die at random. 

Kastrull
![image](https://github.com/user-attachments/assets/0f087cb6-9979-4e13-b36b-f2ee1ea53df3)

### Reproduction steps

.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by itchyOwl** [comment]
It's intentional that Thalamus can be killed by draining the brain room. Probably not that relevant "feature", though. I think it's just natural that they need water to survive. But the technical reason is that if the room is dry, the cells protecting the brain will die. So dry brain rooms are an issue even if we'd make the brain not take damage from the water.

There's a check that should prevent brain from being spawned in rooms that can naturally be drained, like on that picture:
![image](https://github.com/user-attachments/assets/72648114-f858-4532-955d-51002f7ad866)
