### ISSUE TITLE
Storing Items in lockers with Unauthorized Access

### ISSUE THREAD

**Issue by Dstough** [FakeFishGames/Barotrauma#9680]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While exploring a ruined ship, I miss-clicked and was able to store a cargo scooter in a Secure Steel Locker. This Cargo scooter had the key card that would normally grant access to the locker inside it already. This permanently locked us out of that locker. We ran some further tests and found that we were able to store a key card in the locker even though we didn't have access to it.

It would seem that you are able to drag items into a locker and store them there as long as there is space in there even when you do not have access to them.

### Reproduction steps

1. Find a Secure Steel Locker on a wrecked submarine.
2. Get the ID card to give you access to that locker.
3. Place the ID card in a cargo scooter.
4. Drag the cargo scooter over the Secure Steel Locker.

### Bug prevalence

Just once

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Dstough** [comment]
For clarification, we were able to drag a different key card into the locker after the cargo scooter (the one with the proper id card) was already in it.

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.15.1 - you don't even need to use a container for this or second ID card, you can store the ID card (And that is the only one, no others) itself that grants you the access from any slot into a locked container. then the container will take the card and lock you out at the same time as you no longer have the required tags/item.

**Comment by kumilanka** [comment]
Can't repro the bug, need more info or clearer steps to repro.

**Comment by NilanthAnimosus** [comment]
Reproduced on 0.18.15.1 and against release/Summer-Update commit https://github.com/FakeFishGames/Barotrauma-development/commit/7e226fa509499eed3d6667ccc08fd6670d7062d0

Needed to use a ID with access to secure storage, and any other ID card (might not be necessary? but had one anyways) that doesn't have access to said secure storage. Have a storage container in hands that can be placed into the secure storage and place your ID card inside, this should close the interface and you won't be able to drag items over the secure storage in world to place them (and without the UI, cannot drag inside normally). However if you do not deselect it you may then double click to "quickly store" it inside the secure locker you otherwise cannot access.

So reproduction steps:
1. Start in a submarine like dugong (or any with a secure locker in its armoury really)
2. If you want to try multiple ways of getting the ID card back out of the locker, I Recommend spawning a securityofficer inside the sub and placing the ID card inside some other nearby container (so you can repeat the issue easily)
3. control the captain
4. Spawn a "storage container" into inventory of captain
5. Take an ID card from an engineer (or other without access to locker) into captain inventory
6. Select (open UI) of the secure locker in the submarine (IE. armoury)
7. Place Captain ID into storage container in hands, UI should disappear and items can no longer be dragged into the secure locker (Note: they may still drag to another nearby container like dugong has, make sure to read the text)
8. without clicking anywhere (so secure locker still selected) double click the storage container, this will store it into the secure locker you do not have access to.

Video of issue on 0.18.15.1 (fundamentally the same as current code):

https://github.com/FakeFishGames/Barotrauma/assets/29177976/ff48cc56-7495-4776-a8a9-ba7782e75efa

**Comment by kumilanka** [comment]
Ah, I see now. There are even simpler steps to reproduce this issue now that I know what's happening:

1. Be captain aboard Dugong or Typhon2 or any with secure steel cabinet
2. Open secure steel cabinet (you have access via your captain id)
3. With cabinet UI open, toss id card on the floor by drag drop. Cabinet UI closes, but character stays engaged with the cabinet (hand stretched, pulled toward it)
4. Double-click any item in captain's inventory to place it into the secure steel cabinet (if there is room)
5. Pick up id card (cabinet UI re-opens)
6. Get captain's stuff from the cabinet
